server:
  port: 88

# druid
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://58330c2a49bed.gz.cdb.myqcloud.com:15566/moneybook?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: cdb_outerroot
      password: admin123456

      # 连接池初始化、最小、最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 获取连接等待的超时时间
      maxWait: 60000
      # 间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 一个连接在池中最小生存的时间，单位毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mappers/*.xml
